version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pokedex
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./pokedex_data.sql:/docker-entrypoint-initdb.d/pokedex_data.sql

volumes:
  mysql-data:
